name: flutter_catalog
description: Flutter Widget Catalog Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dio: ^5.0.2
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  get_storage: ^2.1.1
  injectable: ^2.1.0
  intl: ^0.17.0
  package_info_plus: ^3.0.3
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^6.0.0+1
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
